services:
  - type: web
    name: computer-lab-inventory-frontend
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build:prod
    staticPublishPath: ./dist/angular-signup-verification-boilerplate
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: "true"
      - key: NPM_CONFIG_AUDIT
        value: "false" 