services:
  - type: web
    name: computer-lab-inventory-frontend
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./dist/angular-signup-verification-boilerplate
    envVars:
      - key: NODE_VERSION
        value: 18.0.0 